version: '3.2'

services:
  db:
    image: postgres:14.2
    privileged: true
    ports:
      - "5432:5432"
    env_file:
      - .env
  #    environment:
  #      POSTGRES_USER: kpk
  #      POSTGRES_PASSWORD: pass
  #      POSTGRES_DB: sportcars
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db